### ISSUE TITLE
Download ODM from Overdrive

### ISSUE THREAD

**Issue by mgiampapa** [brianpipa/OverdriveMP3Downloader#1]
Also not really an issue, I'm old and don't really grock github, but here is some javascript to use as a bookmarklett to download the ODM file from Overdrive. Not my code...

https://gist.github.com/ping/b58ae66359691db1d08f929a9e57a03d

Much simpler than in your instructions.

**Comment by brianpipa** [comment]
Yeah I know about that. Doesn't seem easier to me and in fact, seems more complicated for non tech people.

But I appreciate the feedback
